ekf_filter_node:
  ros__parameters:
    use_sim_time: false
    frequency: 30.0  # Saniyede 30 kez çalış
    sensor_timeout: 0.1
    two_d_mode: true # Araç yerde gidiyor (Z eksenini sabitle)
    
    # Koordinat Çerçeveleri (LidarSetup'taki NDT ile uyumlu)
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom  # EKF'nin merkezi Odom olacak

    # 1. KAYNAK: GPS'ten Çevrilmiş Odometri
    odom0: /odometry/gps
    odom0_config: [true,  true,  false,  # X, Y kullan, Z kullanma
                   false, false, false,  # Roll, Pitch, Yaw kullanma
                   false, false, false,
                   false, false, false,
                   false, false, false]
    odom0_differential: false

    # 2. KAYNAK: STM32'den Gelen IMU
    imu0: /imu/data
    imu0_config: [false, false, false,
                  false, false, true,    # Sadece YAW (Dönüş/Pusula) kullan
                  false, false, false,
                  false, false, true,    # YAW Hızı (Açısal hız) kullan
                  true,  true,  false]   # X ve Y İvmesini kullan
    imu0_differential: false
    imu0_relative: true
    
    # IMU verisini base_link koordinatına uydur
    publish_tf: true

navsat_transform:
  ros__parameters:
    use_sim_time: false
    frequency: 30.0
    delay: 3.0
    magnetic_declination_radians: 0.096 # İzmir için yaklaşık manyetik sapma (Önemli!)
    yaw_offset: 0.0
    zero_altitude: true
    broadcast_cartesian_transform: true
    publish_filtered_gps: true

    
